version: '2'
services:
  neo4j:
      image: neo4j:latest
      env_file:
        - '.env'
      ports:
        - '7476:7474'
        - '7689:7687'
      volumes:
        - 'pigeondb:/data'

  mongodb:
    image: mongo:latest
    env_file:
      - '.env'
    ports:
      - "27019:27017"
    volumes:
      - 'mongodb:/data'

volumes:
  'pigeondb':
  'mongodb':